import Head from 'next/head';
import Navigation from '../app/src/components/Navigation';
import Badge from '../app/src/components/ui/Badge';
import Card from '../app/src/components/ui/Card';
import CardLink from '../app/src/components/ui/CardLink';

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Eventz-Generated App</title>
        <meta name="description" content="Generated by Eventz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navigation />

      <main className="mx-auto max-w-6xl px-4 pb-16">
        <section className="mt-12 grid gap-10 lg:grid-cols-[1.1fr_0.9fr] lg:items-start">
          <div className="space-y-6">
            <Badge variant="muted">Eventz</Badge>
            <h1 className="text-3xl font-semibold text-slate-900 sm:text-4xl lg:text-5xl">
              Welcome to your Eventz-generated Next.js app
            </h1>
            <p className="text-base text-slate-600">
              This cockpit lets you trigger commands and explore slices in a focused, readable space.
            </p>
            <div className="flex flex-wrap gap-3">
              <Badge className="px-4 py-2">Commands</Badge>
              <Badge className="px-4 py-2">Events</Badge>
              <Badge className="px-4 py-2">Readmodels</Badge>
            </div>
          </div>
          <Card>
            <div className="flex items-center justify-between">
              <h2 className="text-sm font-semibold uppercase tracking-[0.3em] text-slate-500">Slices</h2>
              <span className="text-xs text-slate-400">Ready</span>
            </div>
            <ul className="mt-4 grid gap-3">
              <li><CardLink href="/admin-connection">Admin Connection</CardLink></li>
            <li><CardLink href="/admin-connecte">Admin Connecté</CardLink></li>
            <li><CardLink href="/entreprise-a-retrouver-api">Entreprise A Retrouver API</CardLink></li>
            <li><CardLink href="/liste-des-entreprises">Liste des entreprises</CardLink></li>
            <li><CardLink href="/prepare-invitation">Prepare Invitation</CardLink></li>
            <li><CardLink href="/invitation-a-envoyer">invitation à envoyer</CardLink></li>
            <li><CardLink href="/processor-smtp">processor SMTP</CardLink></li>
            <li><CardLink href="/client-creation-compte">Client Création Compte</CardLink></li>
            <li><CardLink href="/client-a-authentifie">client à authentifié</CardLink></li>
            <li><CardLink href="/client-authentification-auth0">Client Authentification Auth0</CardLink></li>
            <li><CardLink href="/projet-a-recuperer">projet à récupérer</CardLink></li>
            <li><CardLink href="/projet-requete-api-boond">Projet Requête API boond</CardLink></li>
            <li><CardLink href="/projet-recupere-depuis-boond">projet récupéré depuis Boond</CardLink></li>
            <li><CardLink href="/facture-a-recuperer">facture A récupérer</CardLink></li>
            <li><CardLink href="/requete-facture-api-boond">Requête Facture API Boond</CardLink></li>
            <li><CardLink href="/liste-des-factures-depuis-boond">Liste des factures depuis boond</CardLink></li>
            </ul>
            <p className="mt-6 text-xs text-slate-500">
              Get started by editing <code className="font-semibold text-slate-700">pages/index.tsx</code>.
            </p>
          </Card>
        </section>
      </main>
    </div>
  );
}
