import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Eventz-Generated App</title>
        <meta name="description" content="Generated by Eventz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to your Eventz-generated Next.js app!
        </h1>

        <p>
          Get started by editing{' '}
          <code>pages/index.tsx</code>
        </p>
      </main>
    </div>
  );
}
